import React from 'react';

const RigorSection: React.FC = () => {
  return (
    <section id="rigor" className="website-section">
      <div className="section-label">Epistemic Verification</div>
      <h2 className="section-title">Mathematical Rigor & Ṛta-Score Calibration</h2>
      <p className="section-desc">
        NALA computes a real-time Ṛta-Score ($0.0 \rightarrow 1.0$) evaluating logical consistency, empirical assertion check, and state safety before committing every execution step.
      </p>

      <div style={{ marginTop: '48px', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '32px' }}>
        <div className="feature-card" style={{ background: '#111827', color: '#FAF9F6' }}>
          <div style={{ color: '#E8791A', fontSize: '12px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.2em' }}>
            Ṛta-Score Reliability Metric
          </div>
          <div style={{ fontFamily: 'var(--font-serif)', fontSize: '48px', color: '#E8791A', margin: '12px 0' }}>
            RTA = 0.91 +
          </div>
          <p style={{ color: 'rgba(255, 255, 255, 0.7)', fontSize: '14px', lineHeight: 1.6 }}>
            Continuous real-time calibration measuring direct observation (Pratyakṣa) vs logical inference (Anumāna). Ensures zero unverified state mutations.
          </p>
        </div>

        <div className="feature-card">
          <span className="card-num">01</span>
          <h3 className="card-title">Deterministic AST Validation</h3>
          <p className="card-body">
            Every code snippet generated by NALA undergoes formal abstract syntax tree parsing and sandbox dry-runs prior to execution.
          </p>
        </div>

        <div className="feature-card">
          <span className="card-num">02</span>
          <h3 className="card-title">Multi-Model Consensus</h3>
          <p className="card-body">
            Critical decisions require cross-model verification across Gaṇeśa (Fast Router), Sarasvatī (Deep Reasoning), and Śiva (Validator).
          </p>
        </div>
      </div>
    </section>
  );
};

export default RigorSection;
